# Generated by Django 3.2.5 on 2021-08-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='new title', max_length=200)),
                ('description', models.TextField(default='new description')),
                ('auction_image', models.ImageField(upload_to='images/')),
                ('min_bid_price', models.IntegerField(default=0)),
            ],
        ),
    ]
