# Generated by Django 3.2.5 on 2021-08-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auction_image',
            field=models.ImageField(upload_to='auct'),
        ),
    ]
