# Generated by Django 3.2.5 on 2021-08-26 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210826_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 26, 11, 54, 33, 128839)),
        ),
    ]
