# Generated by Django 3.2.5 on 2021-08-28 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210829_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 29, 0, 53, 12, 393289)),
        ),
    ]
