# Generated by Django 3.2.5 on 2021-09-03 00:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_auction_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='min_bid_price',
            new_name='min_price',
        ),
        migrations.AlterField(
            model_name='auction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 3, 2, 43, 16, 813345)),
        ),
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_item', to='auctions.auction')),
            ],
        ),
    ]
