# Generated by Django 3.2.5 on 2021-09-05 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_auction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 6, 0, 24, 40, 326610)),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='bid_amount',
            field=models.CharField(default='Enter your bidding here...', max_length=200),
        ),
    ]
