# Generated by Django 3.2.5 on 2021-09-07 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_auto_20210907_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidding',
            name='bid_count',
        ),
        migrations.AlterField(
            model_name='auction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 7, 14, 49, 11, 478312)),
        ),
    ]
