# Generated by Django 3.2.5 on 2021-09-07 13:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_auto_20210907_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='date',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='listed_by',
        ),
        migrations.CreateModel(
            name='ListDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listed_by', models.CharField(default='', max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 9, 7, 15, 7, 44, 182465))),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_item', to='auctions.auction')),
            ],
        ),
    ]
