# Generated by Django 3.2.5 on 2021-09-08 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0031_auto_20210908_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listdetails',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 8, 14, 5, 43, 666524)),
        ),
    ]
