# Generated by Django 3.2.5 on 2021-09-10 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0035_auto_20210910_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_by',
            field=models.CharField(default='Sender', max_length=200),
        ),
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 10, 14, 25, 46, 643746)),
        ),
        migrations.AlterField(
            model_name='listdetails',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 10, 14, 25, 46, 643746)),
        ),
    ]
