# Generated by Django 3.2.5 on 2021-09-14 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0037_auto_20210914_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='item',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='auction_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='description',
            field=models.TextField(default='new description'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='min_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='title',
            field=models.CharField(default='something new', max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 14, 21, 55, 42, 693816)),
        ),
        migrations.AlterField(
            model_name='listdetails',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 14, 21, 55, 42, 693816)),
        ),
    ]
