# Generated by Django 3.2.5 on 2021-09-16 00:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0040_auto_20210916_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.CharField(choices=[('Books', 'Books'), ('Fashion', 'Fashion')], default='No Category', max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 2, 15, 18, 807018)),
        ),
        migrations.AlterField(
            model_name='listdetails',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 2, 15, 18, 807018)),
        ),
    ]
