# Generated by Django 3.2.5 on 2021-09-16 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0042_auto_20210916_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(choices=[('No Category', 'No Category'), ('Books', 'Books'), ('Fashion', 'Fashion'), ('Electronics', 'Electronics'), ('Accessories', 'Accessories')], default='No Category', max_length=150),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 9, 17, 11, 312630)),
        ),
        migrations.AlterField(
            model_name='listdetails',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 9, 17, 11, 312630)),
        ),
    ]
