# Generated by Django 3.2.5 on 2021-09-18 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0045_auto_20210917_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 18, 10, 1, 38, 274836)),
        ),
        migrations.AlterField(
            model_name='auction',
            name='description',
            field=models.TextField(default='Description'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='title',
            field=models.CharField(default='Title', max_length=200),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='bid_amount',
            field=models.CharField(default='Bid_amount', max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(default='Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_by',
            field=models.CharField(default='Comment_by', max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 18, 10, 1, 38, 274836)),
        ),
        migrations.AlterField(
            model_name='listdetails',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 18, 10, 1, 38, 274836)),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='description',
            field=models.TextField(default='Description'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='title',
            field=models.CharField(default='Title', max_length=200),
        ),
    ]
